### ISSUE TITLE
sed error with install.sh command

### ISSUE THREAD

**Issue by cornhundred** [wollmanlab/JSTA#2]
Hi, I'm getting an error when I run ` ./install.sh` with the sed command:

```
$ ./install.sh                                       
gcc -g -fPIC -shared -o get_distances.so get_distances.c
gcc -g -fPIC -shared -o get_number_similar_surroundings.so get_number_similar_surroundings.c
sed: 1: "JSTA.py": invalid command code J
```

I was able to get it to run by manually setting (https://github.com/wollmanlab/JSTA/blob/master/CoreFunctions/JSTA.py#L22) to 

`path_to_file = '/path-to-repo/JSTA/CoreFunctions'`

but it looks like there's an error with the sed command but I'm not sure what the error is (I've only used sed a little).

**Comment by rlittman16** [comment]
I added a fix. It was working on my computers, but its possible you have a different sed config than me. 

Your fix totally works, but is a little inconvenient.

Let me know if its still a problem!

**Comment by cornhundred** [comment]
Thanks that's working now.
