### ISSUE TITLE
parameters for fast_de_all_spots

### ISSUE THREAD

**Issue by lidanwu** [wollmanlab/JSTA#4]
Hello there, 
May I know how you determined the parameters for `fast_de_all_spots(spots, approximate_binsize, bandwidth)`?
The RunningJSTA example uses `approximate_binsize = pixel_length = 1`, while the simulated data is generated with `pixels_per_micron = 2`. Why is that?

I got error shown below when I tried to apply this to my own `spots` data where `z = 1.0` for all rows and `x, y `are in pixel with pixel size = 0.18um. `pixels = fast_de_all_spots(spots, approximate_binsize = 3, bandwidth = 5)`
What might go wrong? Do I have to use `spots` data with a range of z values? Please advise. 
```
print(spots.shape)
print(spots.head(5))

(2734697, 4)
      gene            x            y    z
0    GSTP1  3177.866667  2924.393333  1.0
1  HLA-DRA  2397.000000    20.550000  1.0
2    HLA-A  3997.383333   836.050000  1.0
3     CD68  4536.937500  1477.937500  1.0
4     JUNB   369.138889  3598.227778  1.0
```
Error message: 

> ValueError                                Traceback (most recent call last)
> <ipython-input-82-447f4ebffce5> in <module>
>       5 num_spots_around = 5
>       6 pixel_length = 3
> ----> 7 pixels = fast_de_all_spots(spots, approximate_binsize = 3, bandwidth = 5)
>       8 locations = get_locations(spots, pixel_length)
> 
> E:\for_JISA\JSTA\CoreFunctions\JSTA.py in fast_de_all_spots(spots, approximate_binsize, bandwidth)
>     263         kde_data: 4d array of all kde data for every gene (4th dimension)
>     264     '''
> --> 265     positions, x_shape = get_positions_for_kde(spots, approximate_binsize)
>     266     kde_data = np.zeros((x_shape[0],x_shape[1],x_shape[2],len(np.unique(spots.gene))))
>     267     for i,gene in enumerate(np.unique(spots.gene)):
> 
> E:\for_JISA\JSTA\CoreFunctions\JSTA.py in get_positions_for_kde(spots, approximate_binsize)
>     334     xs = np.arange(np.min(spots.x),np.max(spots.x)+x_steps,x_steps)
>     335     ys = np.arange(np.min(spots.y),np.max(spots.y)+y_steps,y_steps)
> --> 336     zs = np.arange(np.min(spots.z),np.max(spots.z)+z_steps,z_steps)
>     337 
>     338     X, Y, Z = np.mgrid[np.min(spots.x):np.max(spots.x)+x_steps:x_steps,
> 
> ValueError: arange: cannot compute length

**Comment by rlittman16** [comment]
The bin size is the resolution that the pixels are at. The units I was using were in microns, so you would have to convert accordingly. If you use smaller numbers for approximate bin size the resolution is better, but computation is slower. In general I was using bin sizes of 2 or 3 microns.

Regarding the z, since it is supposed to be 3d data I would just repeat your spots with a z above and blow what its at now. It isn't an elegant solution, but it works in practice.

**Comment by lidanwu** [comment]
I see. so for 1 pixel = 0.18um. Do I need to use approximate_binsize = 14 to get 2.52 um? Besides, for the bandwidth, is it really in unit of spot as listed in tutorial example or in pixel? Why you use bandwidth = 5 in the example? Is that determined by the spot density per cell?
Does it matter to use float or integer for x, y of spots data? Should I convert the x, y to um before running the downstream?

**Comment by rlittman16** [comment]
Exactly 14 would get 2.52um.

 The bandwidth isn't that important here. Essentially it is the number of spots it will use as the numerator, and then the denominator is the volume required to get to that number of spots. Higher bandwidths gets more information from farther away, but doesn't end up changing the densities that much. It smooths out the density. 

For x,y it doesn't need to be integers, and doesn't need to be in um as long as the rest of your coordinates, like for nuclei etc. are also in pixels.

**Comment by lidanwu** [comment]
Thank you so much for the prompt replies! The `fast_de_all_spots()` ran with no error after assigning different z values to `spots` data.  Since this step takes long time for high-plexity data, it might be great to add an option of saving the KDE results in files such that one can load it to the workspace when re-doing the analysis. 

One more question, the example uses nuclei coordinates for initialization. Would it be fine to use cell body coordinates (derived from membrane staining with antibodies)? If yes, do I need to change the `dist_threshold` (what unit? is it image pixel or the binsize used in KDE?) for `classify_pixels_to_nuclei(locs, nuclei_clust, dist_threshold)`? The main difference from using cell body coordinates from nuclei coordinates is that true cell boundaries would always be outside nuclei boundaries but might be inside or outside the cell body boundaries. Will that create a problem in JSTA?

**Comment by rlittman16** [comment]
Thanks for the suggestion! I currently use the following to save the output of that result, but I should add it directly to the function.


```
import pickle as pkl
import os
pixel_file = 'path/to/pixels.pkl' #change to your path
locations_file = 'path/to/locations.pkl' # change to your path
if os.path.isfile(pixel_file):
    with open(pixel_file,'rb') as f:
        pixels = pkl.load(f)
    with open(locations_file,'rb') as f:
        locations = pkl.load(f)
else:
    pixels, locations = fast_de_all_spots(...)
    with open(pixel_file,'wb') as f:
        pkl.dump(pixels, f)
    with open(locations_file,'wb') as f:
        pkl.dump(locations, f)
```

For the second question, cell body coordinates would work as well for cell boundaries at or outside of the cell body stained, but anything inside is automatically part of that cell. You could try it using cell centers instead (center of cell body staining), but it might be better to just use the cell body staining by itself if it is fairly accurate.

If you think the cell body staining could be wrong in that the cell border is really inside of what was stained, you could shrink the cell body staining by removing some pixels that are on the outside.

dist_threshold would be in the same units you are using for your spots. The idea is that pixels are initially assigned to their closest cell body, but if it is farther than the dist_threshold from all cell bodies it isn't assigned to any cells.  If you're using cell bodies I'd recomend a small dist_threshold <= 1 micron, as this is just used as the initialization. 

Hope this is all clear, let me know if you have any follow ups!

**Comment by lidanwu** [comment]
Thanks for the explanations and code! 

For the file saving, it would be great if one can save the KDE output for each gene separately and then save the combined KDE file for all genes. This is helpful when one have large number of different genes (transcriptomics level) and the KDE calculation is interrupted during the run somehow. 

Cell body staining is mostly correct except for 2 cases: (1) spots at the junction of two adjacent cells where the cell body staining is kind of merging together (i.e. no clear boundaries) ; (2) cells that are overlaid with each other in z direction. The overlaid region would have mixed signal from the adjacent cells and this is problematic when the overlaid cells are actually of different cell types such that one might mistaken the "contaminated" mixed signal as the biological meaningful signal for cell-cell interaction in space. 

For case (1), shrinking the cell body staining area would help. But does the `approximate_binsize` used for `fast_de_all_spots()` must be smaller than the gap between two adjacent cells? The later classification workflow moves around a full pixel of `approximate_binsize`. if the gap is smaller than `approximate_binsize`, then the downstream classification makes no sense. Right?

If I want to resolve or at least identify/flag case (2) where the "contaminated" mixed signal exists, does it mean I must use nuclei coordinates instead of the cell body coordinates? I'm asking because the "contaminated" mixed signal can happen at both cell body and nuclei regions but with higher probability to occur in cell body region. If that occurs and JSTA is assuming 100% correct assignment for spots overlaid with the provided cell body or nuclei coordinates, downstream classifier would not help with the "contaminated" mixed signal situation. Using cell body coordinates would result in higher chance of wrong spots assignment for case (2). Would you agree on this? What's your suggestions on addressing the case (2) issue?

Or perhaps I could use cell body coordinates in` classify_pixels_to_nuclei(locs, nuclei_clust, dist_threshold)`  but use nuclei coordinates in classifier training step `reclassify_squares(nuc)`. Do you think this might be better than using same coordinates (cell body or nuclei) in both steps?

**Comment by lidanwu** [comment]
I got an error below when doing `fast_de_all_spots(approximate_binsize = 8) `(i.e. 1.5um) for 960 genes. This error shows up after the KDE step finishes as the values for last gene has been printed to screen before this error. But the KDE values is not assigned to `pixel` which is shown as 'not defined'. 
The root cause seems to be that `fast_de_all_spots()` returns only one parameter. Perhaps the script you use is different from the one in master branch. 

> ValueError                                Traceback (most recent call last)
> <ipython-input-28-e36a05b6f1d6> in <module>
>      30         locations = pkl.load(f)
>      31 else:
> ---> 32     pixels, locations = fast_de_all_spots(spots, approximate_binsize = binsize, bandwidth = num_spots_around)
>      33     with open(pixel_file,'wb') as f:
>      34         pkl.dump(pixels, f)
> 
> ValueError: too many values to unpack (expected 2)

**Comment by rlittman16** [comment]
Hello! 

Sorry about that! I just wrote that out quickly, more for the structure of it. Please use the formatting of the code thats in the jupyter notebook. Then you can use that same structure for saving the files. 

That's a very good idea of saving each gene individually. I will implement that. Thanks for the suggestions! 

I think you're right that JSTA's reclassify  squares step may not have that much impact given these cases with the cell body staining. As you mentioned, I would recommend trying out classify_pixels_to_nuclei with the cell body coordinates and use a low dist_threshold. Using just the cell type classifier would help you to annotate your cells based on the reference. If resulting data looks clean then you're done! Otherwise, you may want to reduce cell body staining and try reclassify squares with JSTA. 

Regarding the gap size, generally yes the gap size should be larger than the approximate_binsize. 

In general I also use fewer genes than the entire dataset with JSTA to speed up the computation. I reduce the gene set down to cell type marker genes which can be learned from the single cell reference dataset. I can push a notebook that guides you on this if you'd like some help.

**Comment by lidanwu** [comment]
Thank you so much, Russell. These discussions are very helpful!
It would be fantastic if you can share an example for identifying the cell type marker genes from the reference data. 

Based on the discussions and the paper, it seems that the best workflow should be:
1) `create_celltype_classifier()` from reference scRNA-seq data. 

   - Could we add the functionality of extracting cell type marker genes (or principle components) to `create_celltype_classifier()`? I mean the weight distribution on neutral network classifier should help to identify the key determinants of cell types (or drop the genes with very small contribution to cell type classification). 
   - If yes, we could then use the extracted key determinant of cell types from the initial cell type classifier for downstream analysis. If not, we need to add 1 step before `create_celltype_classifier()` to identify the cell-type marker genes using independent method. 

2) `fast_de_all_spots(approximate_binsize)` on the `spots` data for the extracted key determinants of cell types. 
   - Ideally, the `approximate_binsize` should be smaller than the potential overlaid region of adjacent cells. But this would mean very small `approximate_binsize` and thus extremely long calculation time of `fast_de_all_spots()`. Therefore, it's important to reduce all genes to only the key determinants of cell types for sufficiently fast `fast_de_all_spots()` calculation with relatively small `approximate_binsize` (I'm thinking 0.2~0.5um).
3)  `classify_pixels_to_nuclei(locs, nuclei_clust, dist_threshold)` for initial assignments of `spots` data to each cell/nucleus. 

    - In this step, one can use cell body coordinates as `nuclei_clust` with small `dist_threshold` (<1 `approximate_binsize`). Am I right that for this step, the cell body coordinates could be the non-shrunken ones with some error at cell borders? 

4) `reclassify_squares(nuc, dist_threshold, dist_scaling)` to classify & segment `spots` data. 
   - In this step, one can use eroded/shrunken cell body coordinates as `nuc` with smaller `dist_threshold, dist_scaling` (matching the gap size between adjacent cells in eroded/shrunken cell body coordinates). 
5) determine whether the results look good. If not, repeat step (4) `reclassify_squares() `using even more eroded/shrunken cell body coordinates as `nuc` and larger `dist_threshold, dist_scaling`. 
   - Question: how would you determine whether the results are "clean" enough?
   - I do notice that `reclassify_squares() ` displays `accuracy, val_loss, val_accuracy` as it iterates the train-predict-flip process. Are these 3 good metrics to determine whether the results are "clean" enough? If yes, what threshold values would you use? Besides, it would be great to store the final results of these 3 variables as part of  `reclassify_squares() ` output (in addition to just print them to screen). 

Does the above workflow sound right to you? What are your thoughts on the questions asked above?

Thanks,
Lidan

**Comment by lidanwu** [comment]
One more question, is `fast_de_all_spots(spots, approximate_binsize, bandwidth) `also doing KDE on z direction using same `approximate_binsize `in x y direction? If yes, this is non-ideal as the xy resolution is determined by the optical imaging resolution while the z is often just the z-slice index and the actual distance depends on the z-step size when taking z-imaging stack. If using different `approximate_binsize` in z direction is not an option, is it necessary to convert xyz in same distance unit? is it ok to have z in float?

**Comment by rlittman16** [comment]
Answering the last question first. Yes density estimation is done in z as well, we generally have been using z in the same units as our x and y because we have been mostly using merfish which has depth (z). If it is different slices really far apart in z its probably best to run them separately. 

This order looks good!
1.It is generally difficult to extract interpretable information from neural networks, so I have just been using random forest, and biological annotations for the feature selection step. Feature selection is also a very active area in scRNAseq so you could use other methods as well!

5.That's a good question, and one we don't completely have the answer to. We have been seeing if the data follows known biology i.e. known spatial distribution of cell types, also correlation with scRNAseq cell types. This is why we ended up running simulations, to help prove that JSTA is doing better than watershed. 

Everything else looks good here!

**Comment by lidanwu** [comment]
Sounds great! I'll keep an eye on your future commit on feature selection. I'm closing this issue for now. Thank you so much for the information and discussions.

**Comment by rlittman16** [comment]
@lidanwu  I added an optional step in RunningJSTA.ipynb for doing feature selection
