### ISSUE TITLE
error in get_cell_centers

### ISSUE THREAD

**Issue by lidanwu** [wollmanlab/JSTA#5]
There's 1 typo in `get_cell_centers()` function
https://github.com/wollmanlab/JSTA/blob/master/CoreFunctions/JSTA.py#L75
It should be `cell_centers.append([x_cent, y_cent, z_cent])`

Besides, I have question regarding the `cells_matrix` returned by `reclassify()` function. https://github.com/wollmanlab/JSTA/blob/master/CoreFunctions/JSTA.py#L877
Is this `cells_matrix` the actual gene/molecule count per cell? or the sum of KDE value for each gene for pixels belong to that cell? If it's the latter, how do I convert the KDE value back to the actual gene count per cell?

**Comment by rlittman16** [comment]
Thanks for catching this! 

The cells_matrix is the true counts in the merfish data based on the segmentation map. The KDE values are only used to improve the segmentation boundaries

**Comment by rlittman16** [comment]
The typo is fixed now

**Comment by lidanwu** [comment]
Thanks for the quick reply and the feature selection example. 
Question: how do I get cells_matrix for all genes if I only use a subset of marker genes in reclassify()? 
I suppose `get_matrix_of_cells(pixl_true, cell_assign, nuc)` can do that if `pixel_true` contains all genes and `cell_assign` is output of `reclassify()` using subset of marker genes. If that's correct, then the related suggestion would be to have a function that can subset the output of `fast_de_all_spots() ` for the chosen marker genes.

**Comment by rlittman16** [comment]
Thats exactly right. I've been using the marker genes to get cell_assign, and then running get_matrix_of_cells with pixel_true that have all genes later on. Thats a good idea! Thanks for the input. 

For now I have just been getting the true pixels twice, once for marker genes and once for all genes. It isn't ideal but it works the same.
