### ISSUE TITLE
JSTA runs out of memory during fast_de_all_spots()

### ISSUE THREAD

**Issue by pakiessling** [wollmanlab/JSTA#7]
@rlittman16 Thank you for your help in #6 
Unfortunately, I am running into the next problem.

The fast_de_all_spots() method crashes the program due to out of memory issues even on a 450 GB RAM system.
Memory profiling suggests it is allocating 3000 GB of memory.
Is this a problem with my input?

2048 x 2048 px FOV of a Merfish measurement.
pixel_length = 0.108
num_spots_around = 5

Nuclei:
199,554 rows of pixels of the nuclei segmentation mask, z randomly set to 0/1
Spots:
10423 spots, z randomly set to 0/1
Reference:
3777 rows × 110 columns cell x gene matrix

Any pointers would be greatly appreciated

**Comment by rlittman16** [comment]
Typically I was using a pixel length of 3. This is not the length of the pixel used in the images it's the length of the pixel used when determining the segmentation mask.

 Also how many total genes do you have?

If it is too high I may suggest using marker genes for the segmentation.

**Comment by pakiessling** [comment]
Ah thank you, I assumed it was the microns per pixel of the input nuclei mask.
I get results now for a pixel length of 3. This parameter increases the resolution of the segmentation result, correct?
So start with pixel_length=3 and then decrease if necessary?
What about num_spots_around and max_dist_to_nuclei, could you provide some guidance in selecting a good value?

**Comment by rlittman16** [comment]
I usually just stick with 3 (in microns). Sometimes I will do 2, but the gain is marginal and the computational time is much higher. 

num_spots_around I think I was using 5. If you use higher numbers the gene expression is smoother but less concentrated where the spots may actually be. 5-10 probably works well. 

max_dist_to_nuclei I will use 5 to 10 microns.
